name: Update install.sh Suite

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/install-sh.yml'
      - 'distribution/install.sh'
  workflow_dispatch:


jobs:
  sync-install:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: sudo apt-get install --yes python3-setuptools python3.6-dev
      - run: pip3 install awscli --upgrade --user
      - env:
          AWS_ACCESS_KEY_ID: "${{ secrets.CI_AWS_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}"
        run: make sync-install

  test-install:
    needs:
      - sync-install
    runs-on: ubuntu-20.04
    steps:
      - run: sudo apt-get install --yes curl bc
      - run:  curl --proto '=https' --tlsv1.2 -sSf https://sh.vector.dev | bash -s -- -y
      - run: ~/.vector/bin/vector --version

  install-shell-failure:
    name: install-shell-failure
    if: failure()
    needs:
      - sync-install
      - test-install
    runs-on: ubuntu-20.04
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@0.3.2
      with:
        args: "Update of sh.vector.dev failed: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}>"
