name: Integration Test Suite

on:
  push:
    branches:
      - master
    paths:
      - ".github/workflows/integration-test.yml"
      - ".cargo/**"
      - "benches/**"
      - "lib/**"
      - "proto/**"
      - "scripts/**"
      - "skaffold/**"
      - "src/**"
      - "tests/**"
      - "build.rs"
      - "Cargo.lock"
      - "Cargo.toml"
      - "Makefile"
      - "rust-toolchain"
  workflow_dispatch:

env:
  AUTOINSTALL: true
  AWS_ACCESS_KEY_ID: "dummy"
  AWS_SECRET_ACCESS_KEY: "dummy"
  CONTAINER_TOOL: "docker"
  RUST_BACKTRACE: full
  RUST_TEST_THREADS: 1
  TEST_LOG: vector=debug
  VERBOSE: true
  CI: true
  PROFILE: debug

jobs:
  cancel-previous:
    name: Cancel redundant jobs
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          all_but_latest: true # can cancel workflows scheduled later

  test-integration-aws:
    name: Integration - Linux, AWS
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make ci-sweep
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-aws

  test-integration-clickhouse:
    name: Integration - Linux, Clickhouse
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make ci-sweep
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: make slim-builds
      - run: make test-integration-clickhouse

  test-integration-dnstap:
    name: Integration - Linux, Dnstap
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make ci-sweep
      - uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-dnstap

  test-integration-docker-logs:
    name: Integration - Linux, Docker
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make ci-sweep
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-docker-logs

  test-integration-elasticsearch:
    name: Integration - Linux, ES
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make ci-sweep
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-elasticsearch

  test-integration-fluent:
    name: Integration - Linux, Fluent
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make ci-sweep
      - uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-fluent


  test-integration-eventstoredb_metrics:
    name: Integration - Linux, EventStoreDB Metrics
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make ci-sweep
      - uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-eventstoredb_metrics

  test-integration-gcp:
    name: Integration - Linux, GCP
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make ci-sweep
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-gcp

  test-integration-humio:
    name: Integration - Linux, Humio
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make ci-sweep
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-humio

  test-integration-influxdb:
    name: Integration - Linux, Influx
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make ci-sweep
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-influxdb

  test-integration-kafka:
    name: Integration - Linux, Kafka
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make ci-sweep
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-kafka

  test-integration-logstash:
    name: Integration - Linux, logstash
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make ci-sweep
      - uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-logstash

  test-integration-loki:
    name: Integration - Linux, Loki
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make ci-sweep
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-loki

  test-integration-mongodb_metrics:
    name: Integration - Linux, MongoDB Metrics
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make ci-sweep
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-mongodb_metrics

  test-integration-nats:
    name: Integration - Linux, NATS
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make ci-sweep
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-nats

  test-integration-nginx:
    name: Integration - Linux, Nginx Metrics
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make ci-sweep
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-nginx

  test-integration-postgresql_metrics:
    name: Integration - Linux, PostgreSQL Metrics
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make ci-sweep
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: make slim-builds
      - run: make test-integration-postgresql_metrics


  test-integration-prometheus:
    name: Integration - Linux, Prometheus
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make ci-sweep
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-prometheus

  test-integration-pulsar:
    name: Integration - Linux, Pulsar
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make ci-sweep
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-pulsar

  test-integration-splunk:
    name: Integration - Linux, Splunk
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      - run: make ci-sweep
      - uses: actions/cache@v2.1.6
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-splunk

  test-integration-redis:
    name: Integration - Linux, Redis
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: make ci-sweep
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test-integration-redis

  master-failure:
    name: master-failure
    if: failure() && github.ref == 'refs/heads/master'
    needs:
      - cancel-previous
      - test-integration-aws
      - test-integration-clickhouse
      - test-integration-dnstap
      - test-integration-docker-logs
      - test-integration-elasticsearch
      - test-integration-gcp
      - test-integration-humio
      - test-integration-influxdb
      - test-integration-kafka
      - test-integration-loki
      - test-integration-pulsar
      - test-integration-redis
      - test-integration-splunk
    runs-on: ubuntu-20.04
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@0.3.2
      with:
        args: "Master integration tests failed: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}>"
