name: Test Suite

on:
  pull_request: {}
  push:
    branches:
      - master

env:
  AUTOINSTALL: true
  AWS_ACCESS_KEY_ID: "dummy"
  AWS_SECRET_ACCESS_KEY: "dummy"
  CONTAINER_TOOL: "docker"
  RUST_BACKTRACE: full
  RUST_TEST_THREADS: 1
  TEST_LOG: vector=debug
  VERBOSE: true
  CI: true
  PROFILE: debug
  RUSTFLAGS: "-D warnings"

jobs:
  cancel-previous:
    name: Cancel redundant jobs
    runs-on: ubuntu-20.04
    timeout-minutes: 3
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          all_but_latest: true # can cancel workflows scheduled later

  changes:
      runs-on: ubuntu-20.04
      # Set job outputs to values from filter step
      outputs:
        source: ${{ steps.filter.outputs.source }}
        dependencies: ${{ steps.filter.outputs.dependencies }}
        internal_events: ${{ steps.filter.outputs.internal_events }}
        helm: ${{ steps.filter.outputs.helm }}
      steps:
      - uses: actions/checkout@v2.4.0
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            source:
              - ".github/workflows/test.yml"
              - ".cargo/**"
              - "benches/**"
              - "lib/**"
              - "proto/**"
              - "scripts/**"
              - "skaffold/**"
              - "src/**"
              - "tests/**"
              - "build.rs"
              - "Cargo.lock"
              - "Cargo.toml"
              - "Makefile"
              - "rust-toolchain"
            deny:
              - 'deny.toml'
            dependencies:
              - 'Cargo.toml'
              - 'Cargo.lock'
              - 'rust-toolchain'
              - '.github/workflows/pr.yml'
              - 'Makefile'
              - 'scripts/cross/**'
            internal_events:
              - 'src/internal_events/**'
            helm:
              - 'distribution/helm/**'
            docker:
              - 'distribution/docker/**'

  # Remove this once https://github.com/timberio/vector/issues/3771 is closed.
  # Then, modify the `cross-linux` job to run `test` instead of `build`.
  test-linux:
    name: Unit - x86_64-unknown-linux-gnu
    runs-on: [self-hosted, linux, x64, general]
    needs: changes
    if: ${{ needs.changes.outputs.source == 'true' }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/cache@v2.1.6
        name: Cache Cargo registry + index
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      # We always make sure to stop any previous sccache process before starting it fresh, that
      # way we can be sure we're using the right credentials for storage, etc.
      - name: Start sccache
        env:
          SCCACHE_REDIS: ${{ secrets.SCCACHE_REDIS }}
          SCCACHE_IDLE_TIMEOUT: 0
        run: |
          sccache --stop-server || true
          sccache --start-server
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
      - run: make slim-builds
      - run: make test
        env:
          CARGO_BUILD_JOBS: 5
      - name: Stop sccache
        run: sccache --stop-server

  test-misc:
    name: Miscellaneous - Linux
    runs-on: [self-hosted, linux, x64, general]
    needs: changes
    if: ${{ needs.changes.outputs.source == 'true' }}
    steps:
      - uses: actions/checkout@v2.4.0
      - run: make ci-sweep
      - uses: actions/cache@v2.1.6
        name: Cache Cargo registry + index
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      # We always make sure to stop any previous sccache process before starting it fresh, that
      # way we can be sure we're using the right credentials for storage, etc.
      - name: Start sccache
        env:
          SCCACHE_REDIS: ${{ secrets.SCCACHE_REDIS }}
          SCCACHE_IDLE_TIMEOUT: 0
        run: |
          sccache --stop-server || true
          sccache --start-server
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
      - run: make slim-builds
      - run: make test-shutdown
      - run: make test-cli
      - run: make test-behavior
      - run: make check-examples
      - name: Stop sccache
        run: sccache --stop-server

  cross-linux:
    name: Cross - ${{ matrix.target }}
    runs-on: ubuntu-20.04
    needs: changes
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-musleabihf

    # We run cross checks when dependencies change to ensure they still build.
    # This helps us avoid adopting dependencies that aren't compatible with other architectures.
    if: ${{ needs.changes.outputs.dependencies == 'true' }}
    steps:
      - uses: actions/checkout@v2.4.0
      - run: make ci-sweep
      - uses: actions/cache@v2.1.6
        name: Cache Cargo registry + index
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      # Why is this build, not check? Because we need to make sure the linking phase works.
      # aarch64 and musl in particular are notoriously hard to link.
      # While it may be tempting to slot a `check` in here for quickness, please don't.
      - run: make cross-build-${{ matrix.target }}
      - uses: actions/upload-artifact@v2
        with:
          name: "vector-debug-${{ matrix.target }}"
          path: "./target/${{ matrix.target }}/debug/vector"

  cross-linux-check:
    if: ${{ needs.changes.outputs.dependencies == 'true' }}
    runs-on: ubuntu-latest
    name: Cross - Linux
    needs: cross-linux
    steps:
      - name: Check cross matrix status
        if: ${{ needs.cross-linux.result != 'success' }}
        run: exit 1

  test-mac:
    name: Unit - Mac
    # Full CI suites for this platform were only recently introduced.
    # Some failures are permitted until we can properly correct them.
    continue-on-error: true
    runs-on: macos-latest
    needs: changes
    if: ${{ needs.changes.outputs.source == 'true' }}
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/cache@v2.1.6
        name: Cache Cargo registry + index
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - run: bash scripts/environment/bootstrap-macos-10.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      - run: make slim-builds
      - run: make test
      - run: make test-behavior

  test-windows:
    name: Unit - Windows
    # Full CI suites for this platform were only recently introduced.
    # Some failures are permitted until we can properly correct them.
    continue-on-error: true
    runs-on: [self-hosted, windows, x64, general]
    needs: changes
    if: ${{ needs.changes.outputs.source == 'true' }}
    steps:
      - uses: actions/checkout@v2.4.0
      - run: choco install llvm
      - run: .\scripts\environment\bootstrap-windows-2019.ps1
      # We always make sure to stop any previous sccache process before starting it fresh, that
      # way we can be sure we're using the right credentials for storage, etc.
      - name: Start sccache
        env:
          SCCACHE_REDIS: ${{ secrets.SCCACHE_REDIS }}
          SCCACHE_IDLE_TIMEOUT: 0
        run: |
          sccache --stop-server
          sccache --start-server
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
      - run: make test
      - name: Stop sccache
        run: sccache --stop-server

  test-vrl:
    name: VRL - Linux
    continue-on-error: true
    runs-on: [self-hosted, linux, x64, general]
    needs: changes
    if: ${{ needs.changes.outputs.source == 'true' }}
    steps:
      - uses: actions/checkout@v2.4.0
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      # We always make sure to stop any previous sccache process before starting it fresh, that
      # way we can be sure we're using the right credentials for storage, etc.
      - name: Start sccache
        env:
          SCCACHE_REDIS: ${{ secrets.SCCACHE_REDIS }}
          SCCACHE_IDLE_TIMEOUT: 0
        run: |
          sccache --stop-server || true
          sccache --start-server
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
      - run: make test-vrl
      - name: Stop sccache
        run: sccache --stop-server

  check-component-features:
    name: Component Features - Linux
    runs-on: [self-hosted, linux, x64, general]
    needs: changes
    if: ${{ needs.changes.outputs.source == 'true' }}
    steps:
      - uses: actions/checkout@v2.4.0
      - run: sudo -E bash scripts/environment/bootstrap-ubuntu-20.04.sh
      - run: bash scripts/environment/prepare.sh
      - run: echo "::add-matcher::.github/matchers/rust.json"
      # We always make sure to stop any previous sccache process before starting it fresh, that
      # way we can be sure we're using the right credentials for storage, etc.
      - name: Start sccache
        env:
          SCCACHE_REDIS: ${{ secrets.SCCACHE_REDIS }}
          SCCACHE_IDLE_TIMEOUT: 0
        run: |
          sccache --stop-server || true
          sccache --start-server
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
      - run: cargo install cargo-hack
      - run: make check-component-features
      - name: Stop sccache
        run: sccache --stop-server

  checks:
    name: Checks
    runs-on: ubuntu-20.04
    container: timberio/ci_image
    needs: changes
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          # check-version needs tags
          fetch-depth: 0 # fetch everything
      - uses: actions/cache@v2.1.6
        name: Cache Cargo registry + index
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - name: Enable Rust matcher
        run: echo "::add-matcher::.github/matchers/rust.json"
      - name: Make slim-builds
        run: make slim-builds
      - name: Check code format || needs.changes.outputs.source == 'true'
        if: needs.changes.outputs.source == 'true'
        run: make check-fmt
      - name: Check clippy
        if: needs.changes.outputs.source == 'true'
        run: make check-clippy
      - name: Check version
        run: make check-version
      - name: Check scripts
        run: make check-scripts
      - name: Check helm dependencies
        if: needs.changes.outputs.helm == 'true'
        run: make check-helm-dependencies
      - name: Check helm lint
        if: needs.changes.outputs.helm == 'true'
        run: make check-helm-lint
      - name: Check that Helm template snapshots don't diverge from Helm
        if: needs.changes.outputs.helm == 'true'
        run: make check-helm-snapshots
      - name: Check that generated Kubernetes YAMLs don't diverge from Helm
        if: needs.changes.outputs.helm == 'true'
        run: make check-kubernetes-yaml
      - name: Check events
        if: needs.changes.outputs.source == 'true'
        run: make check-events
      - name: Check cargo deny advisories
        if: needs.changes.outputs.dependencies == 'true' || needs.changes.outputs.deny == 'true'
        uses: EmbarkStudios/cargo-deny-action@v1.2.6
        with:
          command: check advisories
      - name: Check cargo deny licenses
        if: needs.changes.outputs.dependencies == 'true' || needs.changes.outputs.deny == 'true'
        uses: EmbarkStudios/cargo-deny-action@v1.2.6
        with:
          command: check licenses

  master-failure:
    name: master-failure
    if: failure() && github.ref == 'refs/heads/master'
    needs:
      - cancel-previous
      - changes
      - cross-linux
      - test-misc
      - test-linux
      - test-mac
      - test-windows
      - test-vrl
      - check-component-features
      - checks
    runs-on: ubuntu-20.04
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@0.3.2
      with:
        args: "Master tests failed: <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}>"
